services:
  - type: web
    name: ancient-alphabet-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000